### ISSUE TITLE
Misspelled module name

### ISSUE THREAD

**Issue by ErwannLegeay** [jhipster/jhipster-neo4j-app#1]
There is a problem while running the app,

a js module is misspelled : 
/jhipster-neo4j-app-master/src/main/webapp/bower_components/angular-dynamic-locale/src/tmhDinamicLocale.js

tmhDinamicLocale.js should be tmhDynamicLocale.js

Regards

**Comment by pvlastaridis** [comment]
Thanks for you note. Soon I expect I will renew the neo4jhipster to the latest version of jhipster and have it corrected in there
