### ISSUE TITLE
Missing classes

### ISSUE THREAD

**Issue by JCDavie** [jhipster/jhipster-neo4j-app#3]
After trying to get this project running, some of the java classes are missing

ManagedUserDTO
HeaderUtil etc

**Comment by pvlastaridis** [comment]
Did you get an error trying to run it? Maybe the files are missing because of the version. Can you be more specific about it?

**Comment by JCDavie** [comment]
From what I can see, the following files are missing:

com.mycompany.myapp.web.filter.CsrfCookieGeneratorFilter
com.mycompany.myapp.config.JHipsterProperties
com.mycompany.myapp.web.rest.dto.ManagedUserDTO
com.mycompany.myapp.web.rest.util.HeaderUtil
com.mycompany.myapp.web.rest.util.PaginationUtil
com.mycompany.myapp.web.rest.dto.KeyAndPasswordDTO

**Comment by pvlastaridis** [comment]
Hope this is fixed now for you. Still learning Jidea VCS!!
